version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - ./client:/app/client
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      CLIENT_BASE_URL: ${CLIENT_BASE_URL}
      CLIENT_PORT: ${CLIENT_PORT}
    ports:
      - "${API_PORT}:3000"
    depends_on:
      - db
  client:
    stdin_open: true
    build:
      context: ./client/
    command: yarn start
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
    environment: 
      REACT_APP_API_BASE_URL: ${API_BASE_URL}
      REACT_APP_API_PORT: ${API_PORT}
    ports:
      - "${CLIENT_PORT}:3000"
