const SET_EVENTS = 'SET_EVENTS';
const SET_EVENT = 'SET_EVENT';
const ADD_EVENT = 'ADD_EVENT';
const FETCH_EVENTS = 'FETCH_EVENTS';
const UPDATE_EVENT = 'UPDATE_EVENT';
const CREATE_EVENT = 'CREATE_EVENT';
const SET_EVENT_ERRORS = 'SET_EVENT_ERRORS';
const SET_CREATE_EVENT_MODAL = 'SET_CREATE_EVENT_MODAL';
const SET_EVENT_MODAL = 'SET_EVENT_MODAL';

export {
  SET_EVENTS,
  SET_EVENT,
  ADD_EVENT,
  FETCH_EVENTS,
  UPDATE_EVENT,
  CREATE_EVENT,
  SET_EVENT_ERRORS,
  SET_CREATE_EVENT_MODAL,
  SET_EVENT_MODAL,
};
